site_name: MINT
extra_css:
  - assets/versions.css
extra_javascript:
  - assets/versions.js
repo_url: https://github.com/mintproject/MINT_USERGUIDE
edit_uri: edit/master/docs/
nav:
  - Overview: index.md
  - Capabilities:
      - Modeling capabilities: modeling.md
      - Indicators: indicators.md
      - Interventions: interventions.md
  - User guide:
      - User Interface Walkthrough: walkthrough.md
      - Explore Areas: walkthrough/01-exploring-area.md
      - Prepare Models:
          - Overview: walkthrough/02-preparing-models/index.md
          - Browse Models: walkthrough/02-preparing-models/browse-models.md
          - Compare Models: walkthrough/02-preparing-models/compare-models.md
          - Add Models: walkthrough/02-preparing-models/add-models.md
          - Edit Models: walkthrough/02-preparing-models/edit-models.md
          - Configure Models: walkthrough/02-preparing-models/configure-models.md
      - Explore Data: walkthrough/03-exploring-data.md
      - Use Models: walkthrough/04-modeling.md
      - Prepare Reports: walkthrough/05-reporting.md
  - Services:
      - Model Catalog: modelcatalog.md
      - Data Catalog: datacatalog.md
  - Administrator Guide:
      - admin-guide/index.md
      - admin-guide/installation.md
      - admin-guide/authentication.md
      - Catalog configuration:
          - Model Catalog: admin-guide/catalog-configuration/model-catalog-configuration.md
          - Solution Catalog: admin-guide/catalog-configuration/solution-catalog-configuration.md
          - Region configuration: admin-guide/catalog-configuration/region-configuration.md
      - CKAN configuration: admin-guide/ckan-configuration.md
      - Execution configuration:
          - Kubernetes: admin-guide/execution-configuration/execution-configuration-kubernetes.md
          - Tapis: admin-guide/execution-configuration/execution-configuration-tapis.md
    #- admin-guide/configuration.md
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: teal

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      toc_depth: "1-1"
      permalink: true
