apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hasura-{{ include "mint.prefix" . }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  {{- if .enabled }}
  tls:
    - hosts:
      - graphql.{{ $.Values.hostname }}
      secretName: hasura-{{ include "mint.prefix" $ }}-tls-secret
  {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "mint.prefix" . }}-hasura
              port:
                number: 80
      {{- if .Values.hostname }}
      host: graphql.{{ .Values.hostname }}
      {{- end }}
