apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cromo-{{ include "mint.prefix" . }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  {{- if .enabled }}
  tls:
    - hosts:
      - cromo.{{ $.Values.hostname }}
      secretName: cromo-{{ include "mint.prefix" $ }}-tls-secret
  {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "mint.prefix" . }}-cromo
              port:
                number: 80
      {{- if .Values.hostname }}
      host: cromo.{{ .Values.hostname }}
      {{- end }}
