apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-catalog-{{ include "mint.prefix" . }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  {{- if .enabled }}
  tls:
    - hosts:
      - api.models.{{ $.Values.hostname }} 
      secretName: model-catalog-{{ include "mint.prefix" $ }}-tls-secret
  {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "mint.prefix" . }}-model-catalog
              port:
                number: 80
      {{- if .Values.hostname }}
      host: api.models.{{ .Values.hostname }}
      {{- end }}
