apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-{{ include "mint.prefix" . }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  {{- if and .self_signed_cert .secret_name }}
    {{- fail "Cannot set `ingress.tls.secret_name` and `ingress.tls.self_signed_cert` at the same time" }}
  {{- end }}
  {{- if .self_signed_cert }}
  tls:
    - secretName: ui-{{ include "mint.prefix" $ }}-tls-secret
  {{- end }}
  {{- if .secret_name }}
  tls:
    - secretName: {{ .secret_name | quote }}
  {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "mint.prefix" . }}-ui
              port:
                number: 80
      {{- if .Values.hostname }}
      host: {{ .Values.hostname }}
      {{- end }}
