components:
  ui:
    image:
      repository: mintproject/mint-ui-lit
      tag: a4bbdf1b18f1073ce0fd8093ffe679266c9e9caf
      pullPolicy: IfNotPresent
  ensemble_manager:
    image:
      repository: mintproject/ensemble-manager
      tag: 8a3362ef2deb39a12b3751bee0baae873298db38
      pullPolicy: IfNotPresent
    config:
      execution_engine:
        type: "tapis"
        basePath: "https://portals.tapis.io"
      auth:
        client_id: "mint-ensemble-manager-local"
        authorization_url: "https://portals.tapis.io/v3/oauth2/authorize"
        public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw/gduKqo2Pjv6puw1TLxEF/CzVacsBYVGYAeyhNg0opB4ScnDlZhGtG84co/9vBVTtKznoZ+L7a3a4gqFZXY404K0TdkkZkRUWW6uU06oMK22EQxQTCPkI+MgqX6nRE6T2RAixluRGVI2qDP620IFLXJCm7l4ZHCDJITpVADdpAnrDe2y6PuYC9nWz+VXVRNs3rkmEV2aHM6F5PTfT1cOuvWxaDCSdzJUQlUNb2h0fWNVPAz0KETzjx4QQ1XFV5KONaMwSGJ6b4RVefaOVp7fgs35TISiO57pX1Cv9KjW3BFG6CWb2TurLtv4HM+mYIUIk3t1XywUonP1oyXSnwPaQIDAQAB\n-----END PUBLIC KEY-----"
        algorithms: ["RS256"]
  hasura:
    auth:
      # -- Authentication type (jwt or webhook)
      type: webhook
      webhook:
        # -- Webhook URL
        config:
          tapisJwksUri: "https://portals.tapis.io/v3/tenants/portals"
          tapisTokenIssuer: "https://portals.tapis.io/v3/tokens"
