welcome_message: Welcome to MINT
default_user: mint@isi.edu
service:
  type: ClusterIP
  port: 80
hostname: localhost
arm_support: false
components:
  backups:
    enabled: false
  cromo:
    enabled: false
    image:
      repository: mintproject/cromo
      tag: 3c75586989aedf2573c37f5352f960c294377931
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: cromo.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
  mic_ui:
    enabled: false
    image:
      repository: mintproject/mic-web
      tag: a736ac5841d471de4679bec80c13b0fb646ae073
      pullPolicy: IfNotPresent
      environment:
        api_url: null
        airflow_url: https://airflow.mint.isi.edu/api/v1
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 1024Mi
  mic_api:
    enabled: false
    image:
      repository: mintproject/mic-api
      tag: ee71a1a364fc3d384f85243684ad95d37913b049
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: api.mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
  mic_api_db:
    image:
      repository: postgres
      tag: 14.6
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  data_catalog:
    enabled: true
    image:
      repository: mintproject/data-catalog
      tag: 9be70359feabe03ed55bfdbf92c20a7e43ab928b
      pullPolicy: IfNotPresent
    arm_image:
      repository: mintproject/data-catalog
      tag: 8a6af95cae183320d596dc5219f2f76d1f234749
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: datacatalog.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  data_catalog_db:
    image:
      repository: mintproject/data-catalog-db
      tag: 9be70359feabe03ed55bfdbf92c20a7e43ab928b
      pullPolicy: IfNotPresent
    arm_image:
      repository: mintproject/data-catalog-db
      tag: 8a6af95cae183320d596dc5219f2f76d1f234749
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 30Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_endpoint:
    enabled: true
    image:
      repository: mintproject/model-catalog-endpoint
      tag: 29256555a6fbaefae4729d5cd259564708a4ab04
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1000m
        memory: 4Gi
      limits:
        cpu: 2000m
        memory: 5Gi
    environment:
      dataset: modelcatalog
      graph_base: http://endpoint.mint.isi.edu/modelCatalog-1.8.0/data/
      prefix: https://w3id.org/okn/i/mint/
      backup_file: /fuseki-base/seeds/model-catalog.trig
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: endpoint.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 20Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  hasura:
    enabled: true
    image:
      repository: mintproject/graphql-engine
      tag: 0fc7ce2a5098d2e86f1280f6fa70acfc816a531d
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    environment:
      enable_console: true
      enable_dev_mode: false
      unauthorized_role: anonymous
    ingress:
      enabled: true
      className: null
      annotations: {}
      hosts:
        - host: graphql.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  hasura_db:
    image:
      repository: postgis/postgis
      tag: 10-3.2-alpine
      pullPolicy: IfNotPresent
    arm_image:
      repository: imresamu/postgis-arm64
      tag: 12-3.4-alpine
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 30Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_explorer:
    enabled: true
    image:
      repository: mintproject/model-catalog-explorer
      tag: 0b2f9f0a9124076aeb492add2f123d0757066f6b
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  model_catalog_api:
    enabled: true
    api_version: v1.8.0
    image:
      repository: mintproject/model-catalog-fastapi
      tag: c5f784785c52034f75de24c46b89907c74a14312
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    environment:
      context_dir: contexts/
      queries_dir: queries/
    ingress:
      enabled: true
      className: ""
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
      hosts:
        - host: api.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  ui:
    enabled: true
    image:
      repository: mintproject/mint-ui-lit
      tag: 858ce054d1f757d0f6ec3765e878ec54091bb110
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  ensemble_manager:
    enabled: true
    api_version: v1
    image:
      repository: mintproject/ensemble-manager
      tag: 4f9831855f6e6f3cd140871e574566427e061e77
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    environment:
      data_dir: /var/mint
      data_url: http://localhost:30010/data
      parallel: 1
    execution_engine:
      type: localex
      config:
        codedir: /home/node/app/data/code
        datadir: /home/node/app/data/data
        tempdir: /home/node/app/data/temp
        logdir: /home/node/app/data/logs
        dataurl: http://localhost:30010/data
        parallelism: 1
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: ensemble-manager.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
google:
  maps:
    key: AIzaSyAkRnERo4F4dy9AhdrWHAN5vdJWs0vZCgM
secrets:
  database:
    data_catalog:
      username: datacatalog
      password: CHANGEME
      database: datacatalog
    model_catalog_endpoint:
      username: admin
      password: CHANGEME
    hasura:
      username: hasura
      password: CHANGEME
      database: hasura
    mic_api:
      username: mic
      password: CHANGEME
      database: mic
  backups:
    s3:
      access_key: CHANGEME
      secret_key: CHANGEME
      bucket: CHANGEME
      path: CHANGEME
      region: null
      endpoint: example.com
  hasura:
    jwt_secret: '{"type": "RS256", "key": "-----BEGIN CERTIFICATE-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmyQQ56WKKsVCUs8n9swlv5DV7st7UUdvNoDSnwovdU2vinQQ686//vRqlUJ5vpyI7r75qTXCPkXUitDhPvGEMfChnb9tuWdymSyZmMmT+34oaYo/2bGSZjTlLRVfRJjUnFYeWoVLoXVKJolyDWtU6bXbFNnUyysb/6YIpg5sSwxkLs/9yl6HsWdFconxPJO6KmMPSjcOc0fZermNq+cOEvj1OqRhVkxDqBebreI+zcgrJHNSN8d6cxTmfVQl1jIPHvxE5oN7qUdfYmK4D+SOlj8FlkUvwis+3Ix2AQsvNoOD1OzuqUOd/FpXBnEGaeTq9EMwDxplNqltR/qT3/poUwIDAQAB\n-----END CERTIFICATE-----", "allowed_skew": 2}'
    admin_secret: CHANGEME
auth:
  client_id: model_catalog
  url: https://auth.mint.isi.edu/
  realm: production
  ui_client_id: mint-ui
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
