welcome_message: Welcome to MINT
default_user: mint@isi.edu
service:
  type: ClusterIP
  port: 80
hostname: localhost
arm_support: false
components:
  backups:
    enabled: false
  cromo:
    enabled: false
    image:
      repository: mintproject/cromo
      tag: 3c75586989aedf2573c37f5352f960c294377931
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: cromo.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    resources: {}
  mic_ui:
    enabled: false
    image:
      repository: mintproject/mic-web
      tag: a736ac5841d471de4679bec80c13b0fb646ae073
      pullPolicy: IfNotPresent
      environment:
        api_url: null
        airflow_url: https://airflow.mint.isi.edu/api/v1
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  mic_api:
    enabled: false
    image:
      repository: mintproject/mic-api
      tag: ee71a1a364fc3d384f85243684ad95d37913b049
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: api.mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  mic_api_db:
    image:
      repository: postgres
      tag: 14.6
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  data_catalog:
    enabled: true
    image:
      repository: mintproject/data-catalog
      tag: 9be70359feabe03ed55bfdbf92c20a7e43ab928b
      pullPolicy: IfNotPresent
    arm_image:
      repository: mintproject/data-catalog
      tag: 8a6af95cae183320d596dc5219f2f76d1f234749
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "600m"
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: datacatalog.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  data_catalog_db:
    image:
      repository: mintproject/data-catalog-db
      tag: 9be70359feabe03ed55bfdbf92c20a7e43ab928b
      pullPolicy: IfNotPresent
    arm_image:
      repository: mintproject/data-catalog-db
      tag: 8a6af95cae183320d596dc5219f2f76d1f234749
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 30Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_endpoint:
    enabled: true
    image:
      repository: mintproject/model-catalog-endpoint
      tag: 29256555a6fbaefae4729d5cd259564708a4ab04
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "2000Mi"
        cpu: "1000m"
      limits:
        memory: "2500Mi"
        cpu: "1024m"
    environment:
      dataset: modelcatalog
      graph_base: http://endpoint.mint.isi.edu/modelCatalog-1.8.0/data/
      prefix: https://w3id.org/okn/i/mint/
      backup_file: /fuseki-base/seeds/model-catalog.trig
      seeds_url: https://raw.githubusercontent.com/mintproject/model-catalog-endpoint/main/data/model-catalog.trig
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: endpoint.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 20Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  hasura:
    enabled: true
    image:
      repository: mintproject/graphql-engine
      tag: 305c0dbeba1878eafe348f21fc300fbfc017d9dc
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1000m"
      limits:
        memory: "1100Mi"
        cpu: "1100m"
    environment:
      enable_console: true
      enable_dev_mode: false
      unauthorized_role: anonymous
    ingress:
      enabled: true
      className: null
      annotations: {}
      hosts:
        - host: graphql.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  hasura_db:
    image:
      repository: postgis/postgis
      tag: 10-3.2-alpine
      pullPolicy: IfNotPresent
    arm_image:
      repository: imresamu/postgis-arm64
      tag: 12-3.4-alpine
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1000m"
      limits:
        memory: "1100Mi"
        cpu: "1100m"
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 30Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_explorer:
    enabled: true
    image:
      repository: mintproject/model-catalog-explorer
      tag: 0b2f9f0a9124076aeb492add2f123d0757066f6b
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  model_catalog_api:
    enabled: true
    api_version: v1.8.0
    image:
      repository: mintproject/model-catalog-fastapi
      tag: c5f784785c52034f75de24c46b89907c74a14312
      pullPolicy: IfNotPresent
      requests:
        memory: "1024Mi"
        cpu: "1000m"
      limits:
        memory: "1100Mi"
        cpu: "1100m"
    environment:
      context_dir: contexts/
      queries_dir: queries/
    ingress:
      enabled: true
      className: ""
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
      hosts:
        - host: api.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  ui:
    enabled: true
    image:
      repository: mintproject/mint-ui-lit
      tag: 858ce054d1f757d0f6ec3765e878ec54091bb110
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  ensemble_manager:
    enabled: true
    api_version: v1
    image:
      repository: mintproject/ensemble-manager
      tag: be57e330e06c1ba73295b3eb500c352384e9dbca
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1000m"
      limits:
        memory: "1100Mi"
        cpu: "1100m"
    serviceAccountName: default
    environment:
      data_dir: /var/mint
    config:
      data_catalog:
        api: "http://localhost:5000"
        type: "CKAN"
        extra:
          owner_organization_id: "21033e7d-484d-4974-9340-8c5755242c1f"
          owner_provenance_id: "9ef60317-5da5-4050-8bbc-7d6826fee49f"
      data_server:
        type: "S3"
        region: "ap-south-1"
        bucket: "mintdata"

      graphql:
        endpoint: "localhost:30003/v1/graphql"
        enable_ssl: false
        use_secret: true

      execution_engine:
        type: "localex"
        code_dir: "/home/node/app/data/code"
        data_dir: "/home/node/app/data/data"
        temp_dir: "/home/node/app/data/temp"
        log_dir: "/home/node/app/data/logs"
        data_url: "s3://mintdata"
        log_url: "s3://mintdata"
        parallelism: 2
        wings_export_url: ""
        wings_storage: ""
        wings_dot_path: ""
        wings_ont_url: ""
        # tapis properties
        username: ""
        basePath: ""

    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: ensemble-manager.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    persistence:
      enabled: true
      storageClass: ""
      size: 10Gi
      dataSource: {}
      existingClaim: ""
      selector: {}
      annotations:
        helm.sh/resource-policy: keep

external:
  data_catalog:
    url: http://localhost:5000

google:
  maps:
    key: AIzaSyAkRnERo4F4dy9AhdrWHAN5vdJWs0vZCgM

secrets:
  data_catalog:
    ckan:
      api_key: CHANGEME
  data_server:
    s3:
      access_key: CHANGEME
      secret_key: CHANGEME
  database:
    data_catalog:
      username: datacatalog
      password: CHANGEME
      database: datacatalog
    model_catalog_endpoint:
      username: admin
      password: CHANGEME
    hasura:
      username: hasura
      password: CHANGEME
      database: hasura
    mic_api:
      username: mic
      password: CHANGEME
      database: mic
  backups:
    s3:
      access_key: CHANGEME
      secret_key: CHANGEME
      bucket: CHANGEME
      path: CHANGEME
      region: null
      endpoint: example.com
  hasura:
    jwt_secret: '{"type": "RS256", "key": "-----BEGIN CERTIFICATE-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmyQQ56WKKsVCUs8n9swlv5DV7st7UUdvNoDSnwovdU2vinQQ686//vRqlUJ5vpyI7r75qTXCPkXUitDhPvGEMfChnb9tuWdymSyZmMmT+34oaYo/2bGSZjTlLRVfRJjUnFYeWoVLoXVKJolyDWtU6bXbFNnUyysb/6YIpg5sSwxkLs/9yl6HsWdFconxPJO6KmMPSjcOc0fZermNq+cOEvj1OqRhVkxDqBebreI+zcgrJHNSN8d6cxTmfVQl1jIPHvxE5oN7qUdfYmK4D+SOlj8FlkUvwis+3Ix2AQsvNoOD1OzuqUOd/FpXBnEGaeTq9EMwDxplNqltR/qT3/poUwIDAQAB\n-----END CERTIFICATE-----", "allowed_skew": 2}'
    admin_secret: CHANGEME
auth:
  client_id: model_catalog
  url: https://auth.mint.isi.edu/
  realm: production
  ui_client_id: mint-ui
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
