---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mint.prefix" . }}-ensemble-manager-config-map
  namespace: {{ .Release.Namespace }}
data:
   config.json: |
      {
         {{- if eq .Values.service.type "NodePort" }}
         "data_catalog_api": "http://{{ include "mint.prefix" . }}-data-catalog",
         "model_catalog_api": "http://{{ include "mint.prefix" . }}-model-catalog/{{ .Values.components.model_catalog_api.api_version }}",
         "ensemble_manager_api": "http://{{ include "mint.prefix" .}}-ensemble-manager/{{ .Values.components.ensemble_manager.api_version }}",
         "graphql": {
            "endpoint": "{{ include "mint.prefix" . }}-hasura/v1/graphql",
            "enable_ssl": false,
            "use_secret": true
         },

         {{- else if eq .Values.service.type "ClusterIP" }}
            {{- with .Values.components.data_catalog }}
               {{- if  .enabled }}
         "data_catalog_api": "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}",
               {{- end }}
            {{- end }}

            {{- with .Values.components.model_catalog_api }}
               {{- if  .enabled }}
         "model_catalog_api": "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/{{ .api_version }}",
               {{- end }}
            {{- end }}

            {{- with .Values.components.ensemble_manager }}
               {{- if  .enabled }}
         "ensemble_manager_api": "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/{{ .api_version }}",
               {{- end }}
            {{- end }}

            {{- with .Values.components.hasura }}
               {{- if  .enabled }}
         "graphql": {
            "endpoint": "{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/v1/graphql",
            "enable_ssl": {{ if .ingress.tls  }}true{{else}}false{{ end }},
            "use_secret": true
         },
               {{- end }}
            {{- end }}
         {{- end }}


         {{- with .Values.components.ensemble_manager }}
         {{- if eq .execution_engine.type "localex" }}
         "execution_engine": "localex",
         "{{ .execution_engine.type }}":
            {{ .execution_engine.config  | toRawJson | nindent 12}},
         {{- end }}
         {{- end }}
         "auth_server": {{ .Values.auth.url | quote }},
         "auth_realm": {{ .Values.auth.realm | quote }},
         "auth_client_id": {{ .Values.auth.ui_client_id | quote }},
         "visualization_url": "",
         "ingestion_api": ""
      }
