---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mint.prefix" . }}-ensemble-manager-config-map
  namespace: {{ .Release.Namespace }}
data:
   config.json: |
      {
         "data_catalog_api": "http://{{ include "mint.prefix" . }}-data-catalog",
         "model_catalog_api": "http://{{ include "mint.prefix" . }}-model-catalog/{{ .Values.components.model_catalog_api.api_version }}",
         "ensemble_manager_api": "http://{{ include "mint.prefix" .}}-ensemble-manager/{{ .Values.components.ensemble_manager.api_version }}",
         "graphql": {
            "endpoint": "{{ include "mint.prefix" . }}-hasura/v1/graphql",
            "enable_ssl": false,
            "use_secret": true
         },

         {{- with .Values.components.ensemble_manager.config }}
         {{- if .type }}
         "execution_engine": {{ .type | quote }},
         "{{ .type }}":
            {{ .execution_engine | toRawJson | nindent 12}},
         {{- end }}

         {{- end}}

         {{ with .external_services.data_catalog }}
         {{- if eq .ckan }}
         "data_catalog_api": {{ .ckan.url | quote }},
         "data_catalog_type": {{ .ckan.type | quote }},
         "data_catalog_extra": {
            "owner_organization_id": {{ .ckan.extra.owner_organization_id | quote }},
            "owner_provenance_id": {{ .ckan.extra.owner_provenance_id | quote }}
         },
         {{- end}}
         {{end}}

         {{- if eq .Values.components.ensemble_manager.config.data_server.type "S3" }}
         {{- with .Values.components.ensemble_manager.config }}
         "data_server_type": {{ .data_server.type | quote }},
         "data_server": {
            "region": {{ .data_server.region | quote }},
            "bucket": {{ .data_server.bucket | quote }},
         {{- end}}
            "access_key": {{ .Values.secrets.data_server.s3.access_key | quote }},
            "secret_access_key": {{ .Values.secrets.data_server.s3.secret_key | quote }}
         },
         {{- end}}

         "auth_server": {{ .Values.auth.url | quote }},
         "auth_realm": {{ .Values.auth.realm | quote }},
         "auth_client_id": {{ .Values.auth.ui_client_id | quote }},
         "visualization_url": "",
         "ingestion_api": ""
      }
