---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mint.prefix" . }}-ensemble-manager-config-map
  namespace: {{ .Release.Namespace }}
data:
   config.json: |
      {
         {{- if eq .Values.service.type "ClusterIP" }}
            {{- with .Values.components.data_catalog }}
               {{- if  .enabled }}
         "data_catalog_api": "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}",
               {{- end }}
            {{- end }}

            {{- with .Values.components.model_catalog_api }}
               {{- if  .enabled }}
         "model_catalog_api": "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/{{ .api_version }}",
               {{- end }}
            {{- end }}

            {{- with .Values.components.ensemble_manager }}
               {{- if  .enabled }}
         "ensemble_manager_api": "http{{ if .ingress.tls }}s{{ end }}://{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/{{ .api_version }}",
               {{- end }}
            {{- end }}

            {{- with .Values.components.hasura }}
               {{- if  .enabled }}
         "graphql": {
            "endpoint": "{{ with (first .ingress.hosts ) }}{{ .host }}{{ end }}/v1/graphql",
            "enable_ssl": {{ if .ingress.tls  }}true{{else}}false{{ end }},
            "use_secret": true
         },
               {{- end }}
            {{- end }}
         {{- end }}


         {{- with .Values.components.ensemble_manager.config }}
         {{- if .type }}
         "execution_engine": {{ .type | quote }},
         "{{ .type }}":
            {{ .execution_engine | toRawJson | nindent 12}},
         {{- end }}

         {{- if eq .data_catalog.type "CKAN"}}
         "data_catalog_api": {{ .data_catalog.api | quote }},
         "data_catalog_type": {{ .data_catalog.type | quote }},
         "data_catalog_extra": {
            "owner_organization_id": {{ .data_catalog.extra.owner_organization_id | quote }},
            "owner_provenance_id": {{ .data_catalog.extra.owner_provenance_id | quote }}
         },
         {{- end}}
         {{- end}}



         {{- if eq .Values.components.ensemble_manager.config.data_server.type "S3" }}
         {{- with .Values.components.ensemble_manager.config }}
         "data_server_type": {{ .data_server.type | quote }},
         "data_server": {
            "region": {{ .data_server.region | quote }},
            "bucket": {{ .data_server.bucket | quote }},
         {{- end}}
            "access_key": {{ .Values.secrets.data_server.s3.access_key | quote }},
            "secret_access_key": {{ .Values.secrets.data_server.s3.secret_key | quote }}
         },
         {{- end}}

         "auth_server": {{ .Values.auth.url | quote }},
         "auth_realm": {{ .Values.auth.realm | quote }},
         "auth_client_id": {{ .Values.auth.ui_client_id | quote }},
         "visualization_url": "",
         "ingestion_api": ""
      }
