---
{{ if .Values.components.model_catalog_api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mint.prefix" . }}-model-catalog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "http-api"
      port: 80
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ include "helm.model_catalog_api_node_port" . }}
      {{ end }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ include "mint.prefix" . }}-model-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mint.prefix" . }}-model-catalog
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mint.prefix" . }}-model-catalog
  template:
    metadata:
      labels:
        app: {{ include "mint.prefix" . }}-model-catalog
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: model-catalog
          {{- with .Values.components.model_catalog_api  }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: PORT
              value: "3000"
            - name: HASURA_GRAPHQL_URL
              value: {{ .environment.hasura_graphql_url | default (printf "http://%s-hasura/v1/graphql" (include "mint.prefix" $)) | quote }}
            - name: LOG_LEVEL
              value: "{{ .environment.log_level }}"
          {{- end }}
            - name: HASURA_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mint.prefix" . }}-secrets
                  key: hasura_admin_secret
                  optional: true
{{ end }}
