{{- if .Values.components.mic_api.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mint.prefix" . }}-mic-post-install
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-mic-post-install"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-mic
        command: ["/bin/bash"]
        args: ["-c", "yarn migrate "]
        {{- with .Values.components.mic_api }}
        image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
        resources:
          {{- toYaml .resources | nindent 12 }}
        {{ end }}
        env:
          - name: DB_HOST
            value: {{ include "mint.prefix" $ }}-mic-api
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "mint.prefix" . }}-mic-api-db-secrets
                key: database
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "mint.prefix" . }}-mic-api-db-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mint.prefix" . }}-mic-api-db-secrets
                key: password
{{- end }}