{{- if .Values.components.hasura.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mint.prefix" . }}-hasura-post-install
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-hasura-post-install"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-db
        image: busybox
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 110m
            memory: 110Mi
        command: ['sh', '-c', 'until nc -z ${DB_HOST} 5432; do echo waiting for db; sleep 2; done;']
        env:
          - name: DB_HOST
            value: {{ include "mint.prefix" $ }}-hasura
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: ALL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "mint.prefix" . }}-hasura-secrets
                key: username

      containers:
      - name: post-install-hasura
        command: ["/bin/bash"]
        args: ["-c", "env && pushd /hasura && hasura migrate apply && hasura metadata apply && hasura seeds apply"]
        {{- with .Values.components.hasura  }}
        image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
        {{ end }}
        resources:
          {{- toYaml .resources | nindent 12 }}
        {{ end }}
        env:
          - name: HASURA_GRAPHQL_ENDPOINT
            value: http://{{ include "mint.prefix" $ }}-hasura
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "mint.prefix" . }}-hasura-secrets
                key: admin_secret
{{- end }}