welcome_message: Welcome to MINT
default_user: mint@isi.edu
service:
  type: NodePort
  port: 30000
components:
  backups:
    enabled: false
  cromo:
    enabled: true
    image:
      repository: mintproject/cromo
      tag: 3c75586989aedf2573c37f5352f960c294377931
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: cromo.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  mic_ui:
    enabled: true
    image:
      repository: mintproject/mic-web
      tag: 4083fbabb98eb503b554f374e5e310195ad6564a
      pullPolicy: IfNotPresent
      environment:
        api_url: null
        airflow_url: https://airflow.mint.isi.edu/api/v1
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  mic_api:
    enabled: true
    image:
      repository: mintproject/mic-api
      tag: 55ec3e0d8093790404a2466d15a16f19b9977b89
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: api.mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  mic_api_db:
    image:
      repository: postgres
      tag: 14.6
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  data_catalog:
    enabled: true
    image:
      repository: mintproject/data-catalog
      tag: 89bd8354c69923e2da5db1098f8c3c272f59c0c2
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: datacatalog.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  data_catalog_db:
    image:
      repository: mintproject/data-catalog-db
      tag: eb6546857a341b32685d458d656cfc9a1e5abc36
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_endpoint:
    enabled: true
    image:
      repository: mintproject/model-catalog-endpoint
      tag: 29256555a6fbaefae4729d5cd259564708a4ab04
      pullPolicy: IfNotPresent
    environment:
      dataset: modelcatalog
      graph_base: http://endpoint.mint.isi.edu/modelCatalog-1.8.0/data/
      prefix: https://w3id.org/okn/i/mint/
      backup_file: /fuseki-base/seeds/model-catalog.trig
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: endpoint.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  hasura:
    enabled: true
    image:
      repository: mintproject/graphql-engine
      tag: 0fc7ce2a5098d2e86f1280f6fa70acfc816a531d
      pullPolicy: IfNotPresent
    environment:
      enable_console: true
      enable_dev_mode: false
      unauthorized_role: anonymous
    ingress:
      enabled: false
      className: null
      annotations: {}
      hosts:
        - host: graphql.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  hasura_db:
    image:
      repository: postgis/postgis
      tag: 10-3.2-alpine
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_explorer:
    enabled: true
    image:
      repository: mintproject/model-catalog-explorer
      tag: dc2d36c1539d13c423c99a9b505b2950f2473762
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  model_catalog_api:
    enabled: true
    api_version: v1.8.0
    image:
      repository: mintproject/model-catalog-fastapi
      tag: 63e6e9498310027cfdab2e725df5f19e57f3d3f2
      pullPolicy: IfNotPresent
    environment:
      context_dir: contexts/
      queries_dir: queries/
    ingress:
      enabled: false
      className: ''
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: 'true'
      hosts:
        - host: api.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  ui:
    enabled: true
    image:
      repository: mintproject/mint-ui-lit
      tag: ad50868bd4b44b6f964478c4b4096aae032dc254
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  ensemble_manager:
    enabled: true
    api_version: v1
    image:
      repository: mintproject/ensemble-manager
      tag: ea8a4f0a21ed63e60dc4d67edaacfeeef3c12daf
      pullPolicy: IfNotPresent
    environment:
      data_dir: /var/mint
      data_url: http://localhost:30010/data
      parallel: 1
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: ensemble-manager.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
google:
  maps:
    key: CHANGEME
secrets:
  database:
    data_catalog:
      username: datacatalog
      password: CHANGEME
      database: datacatalog
    model_catalog_endpoint:
      username: admin
      password: CHANGEME
    hasura:
      username: hasura
      password: CHANGEME
      database: hasura
    mic_api:
      username: mic
      password: CHANGEME
      database: mic
  backups:
    s3:
      access_key: CHANGEME
      secret_key: CHANGEME
      bucket: CHANGEME
      path: CHANGEME
      region: null
      endpoint: example.com
  hasura:
    jwt_secret: '{"type": "RS256", "key": "-----BEGIN CERTIFICATE-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmyQQ56WKKsVCUs8n9swlv5DV7st7UUdvNoDSnwovdU2vinQQ686//vRqlUJ5vpyI7r75qTXCPkXUitDhPvGEMfChnb9tuWdymSyZmMmT+34oaYo/2bGSZjTlLRVfRJjUnFYeWoVLoXVKJolyDWtU6bXbFNnUyysb/6YIpg5sSwxkLs/9yl6HsWdFconxPJO6KmMPSjcOc0fZermNq+cOEvj1OqRhVkxDqBebreI+zcgrJHNSN8d6cxTmfVQl1jIPHvxE5oN7qUdfYmK4D+SOlj8FlkUvwis+3Ix2AQsvNoOD1OzuqUOd/FpXBnEGaeTq9EMwDxplNqltR/qT3/poUwIDAQAB\n-----END CERTIFICATE-----", "allowed_skew": 2}'
    admin_secret: CHANGEME
auth:
  client_id: model_catalog
  url: https://auth.mint.isi.edu/
  realm: production
  ui_client_id: mint-ui
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
