welcome_message: Welcome to MINT
default_user: mint@isi.edu
service:
  type: NodePort
  port: 30000
components:
  cromo:
    enabled: true
    image:
      repository: mintproject/cromo
      tag: latest
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: cromo.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  mic_ui:
    enabled: true
    image:
      repository: mintproject/mic-web
      tag: 1a143764b17a9786ce1221dfaa601d20fab9675e
      pullPolicy: IfNotPresent
      environment:
        api_url: null
        airflow_url: https://airflow.mint.isi.edu/api/v1
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  mic_api:
    enabled: true
    image:
      repository: mintproject/mic-api
      tag: 11a6993d361e64e53fb81a2da7c838bb58446345
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: api.mic.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  mic_api_db:
    image:
      repository: postgres
      tag: 14.6
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  data_catalog:
    enabled: true
    image:
      repository: mintproject/data-catalog
      tag: 89bd8354c69923e2da5db1098f8c3c272f59c0c2
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: datacatalog.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  data_catalog_db:
    image:
      repository: mintproject/data-catalog-db
      tag: 15f10f5717870ecf1f9e5fb0f193c5ecbf8c2af3
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_endpoint:
    enabled: true
    image:
      repository: mintproject/model-catalog-endpoint
      tag: 4f698c73d4ff48ddd20f31315ea23850df8737d7
      pullPolicy: IfNotPresent
    environment:
      dataset: modelcatalog
      graph_base: http://endpoint.mint.isi.edu/modelCatalog-1.8.0/data/
      prefix: https://w3id.org/okn/i/mint/
      backup_file: /fuseki-base/seeds/model-catalog.trig
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: endpoint.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  hasura:
    enabled: true
    image:
      repository: mintproject/graphql-engine
      tag: 52fe407801c22fb036696daef37ab54b68a275f4
      pullPolicy: IfNotPresent
    environment:
      enable_console: true
      enable_dev_mode: false
      unauthorized_role: anonymous
    ingress:
      enabled: false
      className: null
      annotations: {}
      hosts:
        - host: graphql.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  hasura_db:
    image:
      repository: postgis/postgis
      tag: 10-3.2-alpine
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      dataSource: {}
      existingClaim: ''
      selector: {}
      annotations:
        helm.sh/resource-policy: keep
  model_catalog_explorer:
    enabled: true
    image:
      repository: mintproject/model-catalog-explorer
      tag: 2bc1ec44e5857f4870972367fddf0ca81ed8d27b
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  model_catalog_api:
    enabled: true
    api_version: v1.8.0
    image:
      repository: mintproject/model-catalog-fastapi
      tag: 8a6d3c09d7529d5b7b86e098c08bf69f1df2848d
      pullPolicy: IfNotPresent
    environment:
      context_dir: contexts/
      queries_dir: queries/
    ingress:
      enabled: false
      className: ''
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: 'true'
      hosts:
        - host: api.models.mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  ui:
    enabled: true
    image:
      repository: mintproject/mint-ui-lit
      tag: 80db1b04d820ea3a5beb86bd6dcf4ef041acda0a
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: mint.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
google:
  maps:
    key: CHANGEME
secrets:
  database:
    data_catalog:
      username: datacatalog
      password: CHANGEME
      database: datacatalog
    model_catalog_endpoint:
      username: admin
      password: CHANGEME
    hasura:
      username: hasura
      password: CHANGEME
      database: hasura
    mic_api:
      username: mic
      password: CHANGEME
      database: mic
  hasura:
    jwt_secret: '{"type": "RS256", "key": "-----BEGIN CERTIFICATE-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmyQQ56WKKsVCUs8n9swlv5DV7st7UUdvNoDSnwovdU2vinQQ686//vRqlUJ5vpyI7r75qTXCPkXUitDhPvGEMfChnb9tuWdymSyZmMmT+34oaYo/2bGSZjTlLRVfRJjUnFYeWoVLoXVKJolyDWtU6bXbFNnUyysb/6YIpg5sSwxkLs/9yl6HsWdFconxPJO6KmMPSjcOc0fZermNq+cOEvj1OqRhVkxDqBebreI+zcgrJHNSN8d6cxTmfVQl1jIPHvxE5oN7qUdfYmK4D+SOlj8FlkUvwis+3Ix2AQsvNoOD1OzuqUOd/FpXBnEGaeTq9EMwDxplNqltR/qT3/poUwIDAQAB\n-----END CERTIFICATE-----"}'
    admin_secret: CHANGEME
auth:
  client_id: model_catalog
  url: https://auth.mint.isi.edu/
  realm: production
  ui_client_id: mint-ui
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
